### ISSUE TITLE
Can you please write a tutorial on it on how to use it 

### ISSUE THREAD

**Issue by nikhilpandey4** [thecheatah/SwiftVapor-swagger-codegen#1]
Can you please write a tutorial on how to use it

**Comment by thecheatah** [comment]
@nikhilpandey4 Please take a look at the [README](https://github.com/thecheatah/SwiftVapor-swagger-codegen/blob/master/README.md). Let me know if instructions are unclear.

**Comment by thecheatah** [comment]
I am closing this issue. If the read me is not sufficient, please open an issue with specific gaps.
