### ISSUE TITLE
Service not avalible when attempting to run example

### ISSUE THREAD

**Issue by spprichard** [thecheatah/SwiftVapor-swagger-codegen#2]
When running 
```docker run --rm -v "$(pwd):/output" synology:5350/swagger-codegen/swift/vapor-server-codegen -i api.yaml -o ./VaporTestInterface --additional-properties projectName=VaporTestInterface```

I get back 
```
Unable to find image 'synology:5350/swagger-codegen/swift/vapor-server-codegen:latest' locally
docker: Error response from daemon: Get https://synology:5350/v2/: Service Unavailable.
```

It appears to me, to be an issues trying to find the image. Any thoughts?

**Versions:**
MacOS: 10.15.1
Docker for Desktop: 2.1.0.5
Docker Engine: 19.03.5
Docker Machine: 0.16.2

**Comment by thecheatah** [comment]
@spprichard Please use the following command: 
```sh
docker run --rm -v "$(pwd):/output" thecheatah/vapor-server-codegen:4 -i api.yaml -o ./output --additional-properties projectName=VaporTestInterface
```
I am curious, where did you get the example above? I will replace it in the documentation.

**Comment by thecheatah** [comment]
@spprichard I have updated the example to use the correct docker registry. Thanks for the feedback!

Will close this for now. Feel free to reopen if you run into issues.

**Comment by spprichard** [comment]
The update now works. Thank you for the quick turn around!
